apiVersion: v1
kind: Jaeger
  metadata:
    name: jaeger
    namespace: default
  spec:
    agent:
      config: {}
      options: {}
      resources: {}
    allInOne:
      config: {}
      options: {}
      resources: {}
    collector:
      config: {}
      options: {}
      resources: {}
    ingester:
      config: {}
      options: {}
      resources: {}
    query:
      oauthProxy:
        enabled: true
        args: {}
        image: quay.io/keycloak/keycloak-gatekeeper:10.0.0
      options: {}
      resources: {}